### ISSUE TITLE
xi赛ppt和视频对不上

### ISSUE THREAD

**Issue by YYGe01** [xiaomabenten/system_architect#13]
能给个新版视频和ppt嘛，能对上的那种。

**Comment by xiaomabenten** [comment]
我核对一下，感谢反馈

**Comment by xiaomabenten** [comment]
帅哥，我刚刚挨着挨着看，对的上，因为我把ppt按照章节合并的。你可以看一下，感谢你的反馈！

**Comment by YYGe01** [comment]
> 帅哥，我刚刚挨着挨着看，对的上，因为我把ppt按照章节合并的。你可以看一下，感谢你的反馈！

![image](https://github.com/xiaomabenten/system_architect/assets/45594167/4548d114-11cd-4fd6-8d24-1e4d6e550f27)

你好，请看第13课的视频讲义上找不到。
讲义12页之后就对不上了。

**Comment by xiaomabenten** [comment]
大佬，今晚上会重新更新，麻烦明天重新看一下。感谢你的反馈
