### ISSUE TITLE
pc 版页面显示有问题，麻烦修复

### ISSUE THREAD

**Issue by zhangxianglink** [xiaomabenten/system_architect#15]
![image](https://github.com/user-attachments/assets/678fbb75-40dd-4b37-b0d5-a54e5fca46ae)

**Comment by xiaomabenten** [comment]
已转发给对方了

**Comment by zhangxianglink** [comment]
> 已转发给对方了

bug产生环境：window10, Microsoft Edge
版本 128.0.2739.42 (正式版本) (64 位)

bug 消失：Chrome 已是最新版本
版本 128.0.6613.85（正式版本） （64 位）
