### ISSUE TITLE
跪求2022年12月出版的《系统架构设计师教程（第2版）》

### ISSUE THREAD

**Issue by walkingOnAir** [xiaomabenten/system_architect#5]
跪求2022年12月出版的新版《系统架构设计师考试大纲》和《系统架构设计师教程（第2版）》
感谢大佬！！！！！！

**Comment by lzy19931993** [comment]
大佬有资源了吗？我也想搞一份

**Comment by walkingOnAir** [comment]
> 

留下邮箱，我发你

**Comment by walkingOnAir** [comment]
> 大佬有资源了吗？我也想搞一份

留下邮箱，我发你

**Comment by lzy19931993** [comment]
fly_octopus@hotmail.com 多谢大佬！！！

**Comment by xwsg** [comment]
wsg115@126.com 多谢大佬

**Comment by walkingOnAir** [comment]
系统架构设计师与系统分析...析与解答(2015版).pdf 等文件 https://www.aliyundrive.com/s/Xc8qd3JoTrW 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。




汪鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaomabenten/system_architect"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月27日(星期二) 下午2:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [xiaomabenten/system_architect] 跪求2022年12月出版的《系统架构设计师教程（第2版）》 (Issue #5)





 
***@***.*** 多谢大佬
